obj-$(CONFIG_HPE_GXP_SOCLIB) += gxp-soclib.o
obj-$(CONFIG_HPE_GXP_XREG) += gxp-xreg.o
obj-$(CONFIG_HPE_GXP_FN2) += gxp-fn2.o
obj-$(CONFIG_HPE_GXP_CSM) += gxp-csm.o
obj-$(CONFIG_HPE_GXP_SROM) += gxp-srom.o
obj-$(CONFIG_HPE_GXP_CHIF) += gxp-chif.o
